### ISSUE TITLE
missed case for "if show_on_map==False" in my repo

### ISSUE THREAD

**Issue by Alexey-T** [deepsourcelabs/demo-python#162]
in the
https://github.com/Alexey-T/CudaText/pull/3198/files
your tool missed this case:
![dd](https://user-images.githubusercontent.com/4154978/109280377-01431600-782c-11eb-9563-b3cc8c35c9a0.png)

ie missed second "if n==False"

**Comment by faisal-deepsource** [comment]
Thanks, @Alexey-T for pointing this.

This is a false negative of Flake8. When multiple equality comparisons are present in the same line, only the first occurrence is detected. So, Autofix couldn't work on it.

We have replaced this issue and created a **custom** issue for detecting equality comparisons of singletons. It works for multiple occurrences in the same line. lt should work now. Please try and let me know if you face any problems.

I also raised an [issue](https://github.com/PyCQA/pycodestyle/issues/986) at pycodestyle so flake8 can get this fixed. Thanks again!
